export const itemDetail = {        
    actorsName: "이광수, 김우빈, 디오(D.O), 김기방",
    ageGrade: "15",
    broadEndDate: "",
    broadInfo: "금 오후8:40",
    broadState: "CPBS0200",
    broadcastDate: "20231013",
    categoryCode: "PCD",
    categoryName1: "예능",
    categoryName2: "여행",
    channelCode: "C00551",
    channelName: "tvN",
    contentName: "콩 심은 데 콩 나고 팥 심은 데 팥 난다",
    directorsName: "나영석, 하무성, 변수민",
    duration: 5546,
    episodeSort: "1",
    fanYn: "N",
    frequency: 1,
    genre: "예능",
    story: "이광수, 김우빈, 도경수, 김기방의 코믹 다큐 찐친들의 밭캉스",
    logoImage: "https://image.tving.com/ntgs/contents/CTC/caip/CAIP1800/ko/20231030/0155/P001747179.png",
    mobileThumbnail: "https://image.tving.com/ntgs/contents/CTC/caip/CAIP0400/ko/20231030/0155/P001747179.jpg",
    thumbnail: "https://image.tving.com/ntgs/contents/CTC/caip/CAIP0900/ko/20231030/0155/P001747179.jpg",
    isCinemaSame: false,
    isDrm: false,
    isDubbing: false,
    isEvent: false,
    isExclusive: false,
    isFirstRelease: false,
    isIndividualPurchase: false,
    isOriginal: true,
    isParamount: false,
    isSubtitle: false,
}
