yarnPath: .yarn/releases/yarn-4.0.2.cjs
nodeLinker: pnp
enableGlobalCache: false
plugins:
supportedArchitectures:
    cpu:
        - x64
        - arm64
    os:
        - darwin
        - linux
        - win32
